# Generated by Django 5.1 on 2024-09-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_socio_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, help_text='Cuota mensual para participar en este deporte.', max_digits=8),
        ),
    ]
