# Generated by Django 5.1 on 2024-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_deporte_cuota_mensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='año_nacimiento',
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
