# Generated by Django 5.1 on 2024-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_socio_año_nacimiento_socio_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
